export const ROUTER = {
  SIGNUP_ROUTE: '/signup',
  LOGIN_ROUTE: '/login',
  HOME_PAGE_ROUTE: "/home",
  MENU_PAGE_ROUTE: "/menu",
  SINGLE_MENU_PAGE_ROUTE: "/menu/:id",
  BLOG_LEFTSIDE_PAGE_ROUTE: "/blog-leftside",
  BLOG_RIGHTSIDE_PAGE_ROUTE: "/blog-rightside",
  BLOG_PAGE_ROUTE: "/blog-detail",
  RESERVATION_PAGE_ROUTE: "/reservation",
  ABOUT_PAGE_ROUTE: "/about",
  CHECKOUT_PAGE_ROUTE: "/checkout",
  SHOPPING_CART_ROUTE:"/cart",
  ERROR_PAGE_ROUTE: "/*",
};
